### ISSUE TITLE
GM! Love this product but there is a small visual issue

### ISSUE THREAD

**Issue by GriffGreen** [xvoorvaa/attestation-visualizer#3]
I'm on brave, on a mac.

<img width="447" alt="Screenshot 2023-10-12 at 3 35 10 PM" src="https://github.com/xvoorvaa/attestation-visualizer/assets/14945613/9d715085-429c-432b-9d8b-7188b024c1b6">

I can't see the info on the left

**Comment by xvoorvaa** [comment]
Ah nice catch! I will take a look at it tomorrow!
